/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AtletaController;
import Controller.ComissaoController;
import Controller.EquipeController;
import Factory.DAOFactory;
import java.awt.GraphicsEnvironment;
import javax.swing.JPanel;

/**
 *
 * @author Hendric
 */
public class Ace extends javax.swing.JFrame {

    /**
     * Creates new form Ace
     */
    
    private final int TELA_WIDTH = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getWidth();
    private final int TELA_HEIGHT = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getHeight();
    
    public Ace() {
        initComponents();
        this.setTitle("Ace 2.0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        painelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        cadastroAtleta = new javax.swing.JMenuItem();
        cadastroComissao = new javax.swing.JMenuItem();
        cadastroEquipes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        consultaAtletas = new javax.swing.JMenuItem();
        consultaEquipes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuCriarCampeonato = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        menuCadastro.setText("Cadastro");

        cadastroAtleta.setText("Atletas");
        cadastroAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAtletaActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroAtleta);

        cadastroComissao.setText("Comissao");
        cadastroComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroComissaoActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroComissao);

        cadastroEquipes.setText("Equipes");
        cadastroEquipes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroEquipesActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroEquipes);

        jMenuBar1.add(menuCadastro);

        jMenu3.setText("Consulta");

        consultaAtletas.setText("Atletas");
        consultaAtletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaAtletasActionPerformed(evt);
            }
        });
        jMenu3.add(consultaAtletas);

        consultaEquipes.setText("Equipes");
        consultaEquipes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaEquipesActionPerformed(evt);
            }
        });
        jMenu3.add(consultaEquipes);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Campeonato");

        menuCriarCampeonato.setText("Criar Campeonato");
        menuCriarCampeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCriarCampeonatoActionPerformed(evt);
            }
        });
        jMenu4.add(menuCriarCampeonato);

        jMenuItem4.setText("Registrar Jogos");
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Classificação");
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Relatorios");

        jMenuItem7.setText("Campeonatos");
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("Equipes");
        jMenu5.add(jMenuItem8);

        jMenuItem10.setText("Jogadores");
        jMenu5.add(jMenuItem10);

        jMenuBar1.add(jMenu5);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAtletaActionPerformed
        
        AtletaController atletaController = new AtletaController(new DAOFactory());
        CadastroAtletas telaCadastroAtletas = new CadastroAtletas(atletaController);
        telaCadastroAtletas.setSize(TELA_WIDTH, TELA_HEIGHT);
        painelPrincipal.removeAll();
        painelPrincipal.add(telaCadastroAtletas);
        painelPrincipal.updateUI();
        this.setTitle("Cadastro de Atletas");
    }//GEN-LAST:event_cadastroAtletaActionPerformed

    private void cadastroComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroComissaoActionPerformed
        ComissaoController comissaoController = new ComissaoController(new DAOFactory());
        CadastroComissao telaCadastroComissao = new CadastroComissao(comissaoController);
        telaCadastroComissao.setSize(TELA_WIDTH, TELA_HEIGHT);
        painelPrincipal.removeAll();
        painelPrincipal.add(telaCadastroComissao);
        painelPrincipal.updateUI();
        this.setTitle("Cadastro de Comissão");
    }//GEN-LAST:event_cadastroComissaoActionPerformed

    private void cadastroEquipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroEquipesActionPerformed
        EquipeController equipeController = new EquipeController(new DAOFactory());
        CadastroEquipes telaCadastroEquipe = new CadastroEquipes(equipeController);
        telaCadastroEquipe.setSize(TELA_WIDTH, TELA_HEIGHT);
        painelPrincipal.removeAll();
        painelPrincipal.add(telaCadastroEquipe);
        painelPrincipal.updateUI();
        this.setTitle("Cadastro de Equipes");
    }//GEN-LAST:event_cadastroEquipesActionPerformed

    private void consultaAtletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaAtletasActionPerformed
        AtletaController atletaController = new AtletaController(new DAOFactory());
        ConsultaAtletas telaConsultaAtletas = new ConsultaAtletas(atletaController);
        telaConsultaAtletas.setSize(TELA_WIDTH, TELA_HEIGHT);
        painelPrincipal.removeAll();
        painelPrincipal.add(telaConsultaAtletas);
        painelPrincipal.updateUI();
        this.setTitle("Cadastro de Atletas");
    }//GEN-LAST:event_consultaAtletasActionPerformed

    private void consultaEquipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaEquipesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaEquipesActionPerformed

    private void menuCriarCampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCriarCampeonatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCriarCampeonatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ace().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastroAtleta;
    private javax.swing.JMenuItem cadastroComissao;
    private javax.swing.JMenuItem cadastroEquipes;
    private javax.swing.JMenuItem consultaAtletas;
    private javax.swing.JMenuItem consultaEquipes;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCriarCampeonato;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
