/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CampeonatoController;
import Controller.EquipeCampeonatoController;
import Controller.EquipeController;
import Converter.DateToString;
import Model.Campeonato;
import Model.Equipe;
import static java.awt.Component.TOP_ALIGNMENT;
import java.awt.event.MouseAdapter;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hendric
 */
public class CadastroCampeonatos extends javax.swing.JPanel {

    /**
     * Creates new form CadastroCampeonatos
     */
    
    private final CampeonatoController campeonatoController;
    private final EquipeCampeonatoController equipeCampeonatoController;
    private final EquipeController equipeController;
    private LinkedList<Equipe> equipes;
    private final LinkedList<Equipe> equipesInscritas = new LinkedList<>();
    private Equipe equipe;
    private final DefaultTableModel dtm; 
    private final DefaultTableModel dtmi;
    
    public CadastroCampeonatos(CampeonatoController campeonatoController, EquipeController equipeController, EquipeCampeonatoController equipeCampeonatoController) {
        this.campeonatoController = campeonatoController;
        this.equipeController = equipeController;
        this.equipeCampeonatoController = equipeCampeonatoController;
        initComponents();
        dtmi = (DefaultTableModel) tabelaInscritos.getModel();
        dtm = (DefaultTableModel) tabelaInscrever.getModel();
        listarEquipes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelInfosGerais = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        labelOrganizador = new javax.swing.JLabel();
        campoOrganizador = new javax.swing.JTextField();
        labelTemporada = new javax.swing.JLabel();
        campoTemporada = new javax.swing.JTextField();
        painelInscricao = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaInscrever = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaInscritos = new javax.swing.JTable();
        botaoAdicionar = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();

        painelInfosGerais.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações Gerais"));

        labelNome.setText("Nome");

        labelOrganizador.setText("Organizador");

        labelTemporada.setText("Temporada");

        javax.swing.GroupLayout painelInfosGeraisLayout = new javax.swing.GroupLayout(painelInfosGerais);
        painelInfosGerais.setLayout(painelInfosGeraisLayout);
        painelInfosGeraisLayout.setHorizontalGroup(
            painelInfosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfosGeraisLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(painelInfosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTemporada)
                    .addComponent(labelOrganizador)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelInfosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                    .addComponent(campoOrganizador)
                    .addComponent(campoTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(377, Short.MAX_VALUE))
        );
        painelInfosGeraisLayout.setVerticalGroup(
            painelInfosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfosGeraisLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(painelInfosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelInfosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrganizador)
                    .addComponent(campoOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelInfosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTemporada)
                    .addComponent(campoTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelInscricao.setBorder(javax.swing.BorderFactory.createTitledBorder("Inscrever Equipes"));

        tabelaInscrever.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipe", "Ano de Fundação", "Quant. de Atletas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaInscrever);
        if (tabelaInscrever.getColumnModel().getColumnCount() > 0) {
            tabelaInscrever.getColumnModel().getColumn(0).setResizable(false);
            tabelaInscrever.getColumnModel().getColumn(0).setPreferredWidth(200);
            tabelaInscrever.getColumnModel().getColumn(1).setResizable(false);
            tabelaInscrever.getColumnModel().getColumn(2).setResizable(false);
        }

        tabelaInscritos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipe", "Ano de Fundação", "Quant. de Atletas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaInscritos);
        if (tabelaInscritos.getColumnModel().getColumnCount() > 0) {
            tabelaInscritos.getColumnModel().getColumn(0).setResizable(false);
            tabelaInscritos.getColumnModel().getColumn(0).setPreferredWidth(200);
            tabelaInscritos.getColumnModel().getColumn(1).setResizable(false);
            tabelaInscritos.getColumnModel().getColumn(2).setResizable(false);
        }

        botaoAdicionar.setText(">>");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        botaoRemover.setText("<<");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelInscricaoLayout = new javax.swing.GroupLayout(painelInscricao);
        painelInscricao.setLayout(painelInscricaoLayout);
        painelInscricaoLayout.setHorizontalGroup(
            painelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInscricaoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(botaoAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        painelInscricaoLayout.setVerticalGroup(
            painelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInscricaoLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(botaoAdicionar)
                .addGap(18, 18, 18)
                .addComponent(botaoRemover)
                .addGap(154, 154, 154))
            .addGroup(painelInscricaoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(painelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoSalvar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(painelInfosGerais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelInscricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(painelInfosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoSalvar)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void listarEquipes(){
        try {
            equipes = equipeController.listarTodasEquipes();
            
            DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
            dtcr.setHorizontalAlignment(JLabel.LEFT);
            tabelaInscrever.getColumnModel().getColumn(0).setCellRenderer(dtcr);
            tabelaInscrever.getColumnModel().getColumn(1).setCellRenderer(dtcr);
            tabelaInscrever.getColumnModel().getColumn(2).setCellRenderer(dtcr);
            
            tabelaInscritos.getColumnModel().getColumn(0).setCellRenderer(dtcr);
            tabelaInscritos.getColumnModel().getColumn(1).setCellRenderer(dtcr);
            tabelaInscritos.getColumnModel().getColumn(2).setCellRenderer(dtcr);
            
            atualizarTabelaInscrever(equipes);
            
            tabelaInscrever.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tabelaInscritos.getSelectionModel().clearSelection();
                }
            });
            
            tabelaInscritos.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tabelaInscrever.getSelectionModel().clearSelection();
                }
            });
            
            tabelaInscrever.updateUI();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }        
    }
    
    public void atualizarTabelaInscrever(LinkedList<Equipe> equipes){
        dtm.setRowCount(0);
       
        for(int i = 0; i < equipes.size(); i++){
            try {
                dtm.addRow(new Object[] { equipes.get(i).getNome(),
                    equipes.get(i).getAnoFundacao(),
                    equipeController.getQuantAletasEquipe(equipes.get(i)),
                });
            } catch (SQLException ex) {
                Logger.getLogger(CadastroCampeonatos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }
    
    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if(equipesInscritas.size() < 2){
            JOptionPane.showMessageDialog(this, "Insira mais equipes");
            return;
        }     
        try {
            Campeonato campeonato = new Campeonato();
            campeonato.setNome(campoNome.getText());
            campeonato.setOrganizador(campoOrganizador.getText());
            campeonato.setAnoCampeonato(Integer.parseInt(campoTemporada.getText()));
            campeonato.setEquipes(equipes);
            campeonatoController.cadastrarCampeonato(campeonato);
            
            for(int i = 0; i < equipesInscritas.size(); i++){
                equipeCampeonatoController.inserirEquipeCampeonato(campeonato, equipesInscritas.get(i));
            }
        } catch (SQLException ex) {
            ex.getStackTrace();
        }
        JOptionPane.showMessageDialog(this, "Campeonato criado com sucesso");
        this.removeAll();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        
        for(int i = 0; i < tabelaInscrever.getRowCount(); i++){
            if(tabelaInscrever.isRowSelected(i)){
                dtmi.addRow((Vector) dtm.getDataVector().elementAt(i));
                dtm.removeRow(i);
                equipesInscritas.add(equipes.get(i));
                equipes.remove(i);
            }               
        }
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        for(int i = 0; i < tabelaInscritos.getRowCount(); i++){
            if(tabelaInscritos.isRowSelected(i)){
                dtm.addRow((Vector) dtmi.getDataVector().elementAt(i));
                dtmi.removeRow(i);
                equipes.add(equipesInscritas.get(i));
                equipesInscritas.remove(equipesInscritas.get(i));
            }
        }
    }//GEN-LAST:event_botaoRemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoOrganizador;
    private javax.swing.JTextField campoTemporada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelOrganizador;
    private javax.swing.JLabel labelTemporada;
    private javax.swing.JPanel painelInfosGerais;
    private javax.swing.JPanel painelInscricao;
    private javax.swing.JTable tabelaInscrever;
    private javax.swing.JTable tabelaInscritos;
    // End of variables declaration//GEN-END:variables
}
