/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AtletaController;
import Converter.DateToString;
import Model.Atleta;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.text.MaskFormatter;


/**
 *
 * @author Hendric
 */
public class CadastroAtletas extends javax.swing.JPanel {

    /**
     * Creates new form CadastroAtletas
     */
    
    private final Border bordaPadrao;
    private final AtletaController atletaController;
    private MaskFormatter mascaraData;
    private boolean editando = false;
    private Atleta a;
    
    public CadastroAtletas(AtletaController atletaController) {
        this.atletaController = atletaController; 
        initComponents();   
        try {
            mascaraData = new MaskFormatter("##/##/####");
            mascaraData.setPlaceholderCharacter('_');
            mascaraData.install(campoNascimento);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        labelErro.setVisible(false);
        bordaPadrao = campoAltura.getBorder();
        botaoEditar.setVisible(false);
    }
    
        public CadastroAtletas(AtletaController atletaController, Atleta a) {
        this.atletaController = atletaController; 
        this.a = a;
        initComponents();
        
        campoNome.setText(a.getNome());
        campoCPF.setText(a.getCPF());
        campoAltura.setText(String.valueOf(a.getAltura()));
        campoPeso.setText(String.valueOf(a.getPeso()));
        campoPosicao.setText(a.getPosicao());
        campoRG.setText(a.getRG());
        
        try {
            mascaraData = new MaskFormatter("##/##/####");
            mascaraData.setPlaceholderCharacter('_');
            mascaraData.install(campoNascimento);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        
        campoNascimento.setText(DateToString.dateToString(a.getDataNasc()));
        
        campoNome.setEnabled(false);
        campoCPF.setEnabled(false);
        campoNascimento.setEnabled(false);
        campoAltura.setEnabled(false);
        campoPeso.setEnabled(false);
        campoPosicao.setEnabled(false);
        campoRG.setEnabled(false);
        
        botaoSalvar.setEnabled(false);
        botaoEditar.setVisible(true);
        labelErro.setVisible(false);
        bordaPadrao = campoAltura.getBorder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        campoNome = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        campoRG = new javax.swing.JTextField();
        labelRG = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        campoCPF = new javax.swing.JTextField();
        labelNascimento = new javax.swing.JLabel();
        labelAltura = new javax.swing.JLabel();
        campoAltura = new javax.swing.JTextField();
        labelPeso = new javax.swing.JLabel();
        campoPosicao = new javax.swing.JTextField();
        labelPosicao = new javax.swing.JLabel();
        campoPeso = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        labelErro = new javax.swing.JLabel();
        campoNascimento = new javax.swing.JFormattedTextField();
        botaoEditar = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        labelNome.setText("Nome");

        labelRG.setText("RG");

        labelCPF.setText("CPF");

        labelNascimento.setText("Data de Nascimento");

        labelAltura.setText("Altura");

        labelPeso.setText("Peso");

        labelPosicao.setText("Posição");

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        labelErro.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        labelErro.setForeground(new java.awt.Color(255, 0, 0));
        labelErro.setText("Preencher todos os campos obrigatórios");
        labelErro.setFocusable(false);
        labelErro.setRequestFocusEnabled(false);

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(labelRG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelAltura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelPeso))
                            .addComponent(labelErro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(botaoEditar)
                                .addGap(1, 1, 1)
                                .addComponent(botaoSalvar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelPosicao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRG)
                    .addComponent(labelCPF)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNascimento)
                    .addComponent(campoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAltura)
                    .addComponent(campoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPeso)
                    .addComponent(campoPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPosicao)
                    .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(labelErro)
                    .addComponent(botaoEditar))
                .addContainerGap(216, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if(campoAltura.getText().isEmpty()) campoAltura.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        a.setNome(campoNome.getText());
        a.setDataNasc(new Date(campoNascimento.getText()));
        a.setCPF(campoCPF.getText());
        a.setRG(campoRG.getText());
        a.setAltura(Double.valueOf(campoAltura.getText()));
        a.setPeso(Double.valueOf(campoPeso.getText()));
        a.setPosicao(campoPosicao.getText());
        try {
            if(!editando){
                if(atletaController.cadastrarAtleta(a))
                    System.out.println("Cadastrado com sucesso");
                else
                    System.out.println("Erro ao cadastrar atleta");
            }
            else{
                if(atletaController.atualizarAtleta(a))
                    System.out.println("Atualizado com sucesso");
                else
                    System.out.println("Erro ao atualizar cadastro");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        editando = true;
        campoNome.setEnabled(true);
        campoCPF.setEnabled(true);
        campoNascimento.setEnabled(true);
        campoAltura.setEnabled(true);
        campoPeso.setEnabled(true);
        campoPosicao.setEnabled(true);
        campoRG.setEnabled(true);
        
        botaoSalvar.setEnabled(true);
    }//GEN-LAST:event_botaoEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoAltura;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JFormattedTextField campoNascimento;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPeso;
    private javax.swing.JTextField campoPosicao;
    private javax.swing.JTextField campoRG;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelErro;
    private javax.swing.JLabel labelNascimento;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelPosicao;
    private javax.swing.JLabel labelRG;
    // End of variables declaration//GEN-END:variables
}
