/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AtletaController;
import Converter.DateToString;
import Model.Atleta;
import java.awt.GraphicsEnvironment;
import java.awt.event.MouseAdapter;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hendric
 */
public class ConsultaAtletas extends javax.swing.JPanel {

    private final AtletaController atletaController;
    private final int TELA_WIDTH = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getWidth();
    private final int TELA_HEIGHT = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getHeight();
    private Atleta a;
    
    /**
     * Creates new form ConsultaAtletas
     * @param atletaController Controlador do objeto Atleta
     */
    public ConsultaAtletas(AtletaController atletaController) {
        this.atletaController = atletaController;
        initComponents();
        listarTodosAtletas();
        
    }
    
    public void listarTodosAtletas(){
        try{
            LinkedList<Atleta> atletas = atletaController.consultarTodosAtletas();
            DefaultTableModel dtm = (DefaultTableModel) tabelaAtletas.getModel();
            DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
            dtcr.setHorizontalAlignment(JLabel.LEFT);
            tabelaAtletas.getColumnModel().getColumn(0).setCellRenderer(dtcr);
            

            for(int i = 0; i < atletas.size(); i++){
                String dataNascAtleta = DateToString.dateToString(atletas.get(i).getDataNasc());
                String dataFinal = dataNascAtleta.substring(0, 2) + "/" + dataNascAtleta.substring(2, 4) + "/" + dataNascAtleta.substring(4, 8  );
                dtm.addRow(new Object[] { atletas.get(i).getIdPessoa(),
                                            atletas.get(i).getNome(),
                                            dataFinal
                                        });
            }
            tabelaAtletas.setAlignmentY(TOP_ALIGNMENT);
            tabelaAtletas.updateUI();
            
            tabelaAtletas.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    int row = tabelaAtletas.rowAtPoint(evt.getPoint());
                    
                    int id = Integer.parseInt(dtm.getValueAt(row, 0).toString());
                    atletaSelecionado(id);
                }
            }); 
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public void atletaSelecionado(int id){
        a = atletaController.buscarAtletaID(id);
        CadastroAtletas telaCadastroAtletas = new CadastroAtletas(atletaController, a);
        telaCadastroAtletas.setSize(TELA_WIDTH, TELA_HEIGHT);
        this.removeAll();
        this.add(telaCadastroAtletas);
        this.updateUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAtletas = new javax.swing.JTable();

        tabelaAtletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Data de Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaAtletas);
        if (tabelaAtletas.getColumnModel().getColumnCount() > 0) {
            tabelaAtletas.getColumnModel().getColumn(0).setResizable(false);
            tabelaAtletas.getColumnModel().getColumn(0).setPreferredWidth(25);
            tabelaAtletas.getColumnModel().getColumn(1).setResizable(false);
            tabelaAtletas.getColumnModel().getColumn(1).setPreferredWidth(250);
            tabelaAtletas.getColumnModel().getColumn(2).setResizable(false);
            tabelaAtletas.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaAtletas;
    // End of variables declaration//GEN-END:variables
}
